# Generated by Django 5.2.5 on 2025-08-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='assigmentName',
        ),
        migrations.RemoveField(
            model_name='graded_assignment',
            name='assignmentFile',
        ),
        migrations.RemoveField(
            model_name='graded_assignment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='graded_assignment',
            name='result',
        ),
        migrations.AddField(
            model_name='assignments',
            name='assignmentFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignments',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='result',
            field=models.TextField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='graded_assignment',
            name='assigmentName',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
