# Generated by Django 5.2.5 on 2025-08-19 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_remove_assignments_assigmentname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='flashcardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='study.flashcard')),
            ],
        ),
    ]
