# Generated by Django 5.2.5 on 2025-08-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_flashcardset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignmentFile',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='flashcardSource/'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='inputFile',
            field=models.FileField(blank=True, null=True, upload_to='summarySource/'),
        ),
    ]
